### ISSUE TITLE
if possible set the response field name to lowercase but uppercase ?

### ISSUE THREAD

**Issue by icoco** [ECasio/olingo-spring-example#18]
> {
    "d": {
        "results": [
            {
                "__metadata": {
                    "id": "http://localhost:8080/odata/Mothers(1L)",
                    "uri": "http://localhost:8080/odata/Mothers(1L)",
                    "type": "default.Mother"
                },
                "Id": "1",
                "Name": "Liz",
                "Surname": null
            },
            {
                "__metadata": {
                    "id": "http://localhost:8080/odata/Mothers(2L)",
                    "uri": "http://localhost:8080/odata/Mothers(2L)",
                    "type": "default.Mother"
                },
                "Id": "2",
                "Name": "Liz",
                "Surname": null
            }
        ]
    }
}

the field name always keep uppercase 'Surname',   but most json field will be lowercase : 'surname'

**Comment by EdrilanBerisha** [comment]
I have not tried that.
