### ISSUE TITLE
How to post a mother with her children?

### ISSUE THREAD

**Issue by Ergul** [ECasio/olingo-spring-example#19]

**Comment by EdrilanBerisha** [comment]
Please read the third blog post, there I explain how to do a deep insert (posting parent with children in one POST request)

**Comment by EdrilanBerisha** [comment]
https://blogs.sap.com/2022/08/02/building-an-odata-service-with-a-spring-boot-java-application-using-olingo-part-iii-payloads-and-custom-logic/
