### ISSUE TITLE
Json response 

### ISSUE THREAD

**Issue by arvit1** [ECasio/olingo-spring-example#20]
Ckemi, mund te me ndihmosh duke bere response ne json ose te pakten nje guide qe mund te ndjek per te arritur dicka te tille

**Comment by EdrilanBerisha** [comment]
Hej,

ketu esht nje guide me json response:
- [Building an OData Service with a Spring-Boot Java Application using Olingo – Part I](https://blogs.sap.com/2021/10/29/building-an-odata-service-with-a-spring-java-application-using-olingo-part-i/)
- [Building an OData Service with a Spring-Boot Java Application using Olingo – Part II](https://blogs.sap.com/2022/01/17/building-an-odata-service-with-a-spring-java-application-using-olingo-part-ii/)
- [Building an OData Service with a Spring-Boot Java Application using Olingo – Part III (Payloads and Custom Logic)](https://blogs.sap.com/2022/08/02/building-an-odata-service-with-a-spring-boot-java-application-using-olingo-part-iii-payloads-and-custom-logic/)
